### ISSUE TITLE
Fix global link weight

### ISSUE THREAD

**Issue by espy** [hoodiehq/hoodie-css#9]
Docs had some thicker link styles with thicker underlines, but integrating that into global is a bit more difficult because of the color schemes, which all redefine thickness _and_ color. That should be refactored into sass variables, and color schemes should not reset weights. 

``` css
.docs a{
  font-weight: 400;
  background-size: 1px 2px;
  text-shadow: 2px 0px 0 #FFF, -2px 0 0 #FFF;
  background-position: 0px 1.125em;
}

header.invisible{
  -webkit-transform: translate(0, -102px);
  -ms-transform: translate(0, -102px);
  transform: translate(0, -102px);
}
```

Remember to test underlines on Firefox!
